### ISSUE TITLE
Why don't you use open-rdc organization?

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/HumanoidRobotLibrary#3]
Hi, @RyuYamamoto 

Your repositories are looks like really cool, so that I'd like to suggest that you use open-rdc instead of this one. IMO, it will benefit the future students in our laboratory. I can add your account into that organization if you want.

Thanks,
D

**Comment by RyuYamamoto** [comment]
@DaikiMaekawa I thought trying to add to open-rdc repository, but I was unable to because there is no authority. 

If you are able to add permissions, I think try to add these source code to open-rdc repository.

**Comment by DaikiMaekawa** [comment]
Did you accept my invitation via GitHub? If so, you are able to move the repositories into open-rdc.
Actually, I also recommended to other people what put kind of RDC stuff into one place before. See the link below for more info how to move the repo.

FYI: https://github.com/open-rdc/real-robot-battle/issues/1

**Comment by RyuYamamoto** [comment]
I was able to move this repository to open-rdc.

Thank you, I appreciate it !

**Comment by DaikiMaekawa** [comment]
OK. You have to ask to @yasuohayashibara from next time.

**Comment by yasuohayashibara** [comment]
Thanks, Daiki.
